"""Train, persist, and report on the Phase 3 baseline models."""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import time
from collections.abc import Callable
from pathlib import Path

import joblib
import numpy as np
import sklearn
from numpy.typing import NDArray

from phishguard import __version__
from phishguard.modeling.baselines import (
    BinaryProbabilisticModel,
    build_email_model,
    build_url_model,
    rule_probabilities,
)
from phishguard.modeling.data import ContentType, LabeledText, load_labeled_text
from phishguard.modeling.metrics import binary_metrics, choose_threshold

ModelBuilder = Callable[[int], BinaryProbabilisticModel]


def positive_probabilities(
    model: BinaryProbabilisticModel, texts: list[str]
) -> NDArray[np.float64]:
    """Return phishing-class probabilities from a fitted binary model."""

    matrix = np.asarray(model.predict_proba(texts), dtype=np.float64)
    if matrix.ndim != 2 or matrix.shape != (len(texts), 2):
        raise ValueError(f"Expected a two-column probability matrix, got {matrix.shape}")
    return matrix[:, 1]


def timed_probabilities(
    model: BinaryProbabilisticModel, texts: list[str]
) -> tuple[NDArray[np.float64], float]:
    """Return probabilities and average batch latency per record."""

    start = time.perf_counter()
    probabilities = positive_probabilities(model, texts)
    elapsed = time.perf_counter() - start
    return probabilities, round(elapsed * 1_000 / len(texts), 6)


def artifact_metadata(path: Path) -> dict[str, object]:
    """Return integrity metadata for a locally generated model artifact."""

    digest = hashlib.sha256()
    with path.open("rb") as artifact:
        for chunk in iter(lambda: artifact.read(1024 * 1024), b""):
            digest.update(chunk)
    return {
        "path": str(path),
        "bytes": path.stat().st_size,
        "sha256": digest.hexdigest(),
    }


def train_task(
    content_type: ContentType,
    builder: ModelBuilder,
    train: LabeledText,
    validation: LabeledText,
    test: LabeledText,
    artifact_path: Path,
    seed: int,
) -> dict[str, object]:
    """Fit one baseline, choose its validation threshold, and evaluate its test set."""

    model = builder(seed)
    started = time.perf_counter()
    model.fit(train.texts, train.labels)
    training_seconds = round(time.perf_counter() - started, 3)

    validation_probabilities, validation_latency = timed_probabilities(model, validation.texts)
    threshold, validation_f1 = choose_threshold(validation.labels, validation_probabilities)
    test_probabilities, test_latency = timed_probabilities(model, test.texts)

    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, artifact_path, compress=3)

    rule_validation = rule_probabilities(content_type, validation.texts)
    rule_test = rule_probabilities(content_type, test.texts)
    return {
        "content_type": content_type,
        "training_samples": len(train),
        "validation_samples": len(validation),
        "test_samples": len(test),
        "training_seconds": training_seconds,
        "selected_threshold": round(threshold, 4),
        "selection_metric": "maximum validation F1; recall then proximity to 0.5 break ties",
        "selection_f1": round(validation_f1, 6),
        "ml_model": {
            "validation": binary_metrics(validation.labels, validation_probabilities, threshold),
            "test": binary_metrics(test.labels, test_probabilities, threshold),
            "validation_latency_ms_per_record": validation_latency,
            "test_latency_ms_per_record": test_latency,
        },
        "rule_baseline": {
            "fixed_threshold": 0.5,
            "validation": binary_metrics(validation.labels, rule_validation, 0.5),
            "test": binary_metrics(test.labels, rule_test, 0.5),
        },
        "artifact": artifact_metadata(artifact_path),
    }


def write_markdown_report(report: dict[str, object], path: Path) -> None:
    """Write the portfolio-facing model comparison report."""

    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Baseline Model Evaluation",
        "",
        "> Generated by `python scripts/train_models.py`. Test thresholds were selected",
        "> using validation data only.",
        "",
        "## Test-set results",
        "",
        "| Detector | Approach | Samples | Precision | Recall | F1 | PR-AUC | FPR |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    tasks = report["tasks"]
    if not isinstance(tasks, dict):
        raise TypeError("Expected tasks to be an object")
    for task_name, task_value in tasks.items():
        if not isinstance(task_value, dict):
            raise TypeError(f"Expected task {task_name} to be an object")
        for approach, label in (("ml_model", "ML"), ("rule_baseline", "Rules")):
            result = task_value[approach]
            if not isinstance(result, dict) or not isinstance(result["test"], dict):
                raise TypeError(f"Invalid result for {task_name}/{approach}")
            metrics = result["test"]
            lines.append(
                f"| {task_name} | {label} | {metrics['samples']} | {metrics['precision']} | "
                f"{metrics['recall']} | {metrics['f1']} | {metrics['pr_auc']} | "
                f"{metrics['false_positive_rate']} |"
            )
    lines.extend(
        [
            "",
            "## Evaluation design",
            "",
            "- Email development uses grouped training and validation data; final evaluation",
            "  uses the separate external email source.",
            "- URL development uses domain-grouped training, validation, and untouched test",
            "  partitions.",
            "- The ML threshold is chosen once on validation F1 and carried unchanged to test.",
            "- The rules use a fixed 0.5 threshold and receive no test-set tuning.",
            "- PR-AUC, phishing recall, and false-positive rate are emphasized because accuracy",
            "  can conceal security-relevant errors.",
            "",
            "## Important limitation",
            "",
            "The external email test set contains only 100 unique messages after deduplication",
            "and differs strongly from the training sources. Its metrics are a useful stress test,",
            "not a precise estimate of production performance.",
            "",
            "## Artifact safety",
            "",
            "The four reviewed deployment binaries are versioned with the public repository.",
            "Joblib artifacts use pickle-based loading and must never be replaced with files from",
            "an untrusted source. Their SHA-256 digests and library versions are recorded in the",
            "JSON report and verified before loading.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def train_all(
    processed_dir: Path,
    artifact_dir: Path,
    report_json: Path,
    report_markdown: Path,
    *,
    seed: int = 20260806,
) -> dict[str, object]:
    """Train both baseline tasks and publish aggregate evaluation reports."""

    email_train = load_labeled_text(processed_dir / "train.jsonl", "email")
    email_validation = load_labeled_text(processed_dir / "validation.jsonl", "email")
    email_test = load_labeled_text(processed_dir / "external_test.jsonl", "email")
    url_train = load_labeled_text(processed_dir / "train.jsonl", "url")
    url_validation = load_labeled_text(processed_dir / "validation.jsonl", "url")
    url_test = load_labeled_text(processed_dir / "test.jsonl", "url")

    report: dict[str, object] = {
        "report_version": 1,
        "project_version": __version__,
        "seed": seed,
        "environment": {
            "python": platform.python_version(),
            "scikit_learn": sklearn.__version__,
            "numpy": np.__version__,
        },
        "tasks": {
            "email": train_task(
                "email",
                build_email_model,
                email_train,
                email_validation,
                email_test,
                artifact_dir / "email_baseline.joblib",
                seed,
            ),
            "url": train_task(
                "url",
                build_url_model,
                url_train,
                url_validation,
                url_test,
                artifact_dir / "url_baseline.joblib",
                seed,
            ),
        },
    }
    report_json.parent.mkdir(parents=True, exist_ok=True)
    report_json.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    write_markdown_report(report, report_markdown)
    return report


def main() -> None:
    """Run baseline training from the command line."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--processed-dir", type=Path, default=Path("data/processed"))
    parser.add_argument("--artifact-dir", type=Path, default=Path("artifacts/models"))
    parser.add_argument("--report-json", type=Path, default=Path("reports/model-evaluation.json"))
    parser.add_argument("--report-markdown", type=Path, default=Path("docs/model-evaluation.md"))
    parser.add_argument("--seed", type=int, default=20260806)
    args = parser.parse_args()
    report = train_all(
        args.processed_dir,
        args.artifact_dir,
        args.report_json,
        args.report_markdown,
        seed=args.seed,
    )
    tasks = report["tasks"]
    if not isinstance(tasks, dict):
        raise TypeError("Expected tasks to be an object")
    print(f"trained {', '.join(tasks)} baseline models")


if __name__ == "__main__":
    main()
